apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::556240469610:role/lesson9-eks-nodes-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::556240469610:user/o_shapoval
      username: o_shapoval
      groups:
        - system:masters
    - userarn: arn:aws:iam::556240469610:user/terraform-test-user
      username: terraform-test-user
      groups:
        - system:masters