replicaCount: 2

image:
  repository: 556240469610.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

config:
  SECRET_KEY: "my_secret_key"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,.eu-central-1.elb.amazonaws.com"
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "db-host"
  POSTGRES_PORT: "5432"

nodeSelector: {}
tolerations: []
affinity: {}