apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "django-app.name" . }}
    spec:
      containers:
        - name: django-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.config.DJANGO_SECRET_KEY }}"
            - name: DEBUG
              value: "{{ .Values.config.DJANGO_DEBUG }}"
            - name: ALLOWED_HOSTS
              value: "{{ .Values.config.ALLOWED_HOSTS }}"
            - name: DB_NAME
              value: "{{ .Values.config.DB_NAME }}"
            - name: DB_USER
              value: "{{ .Values.config.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.config.DB_PASSWORD }}"
            - name: DB_HOST
              value: "{{ .Values.config.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.config.DB_PORT }}"