apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
spec:
  project: django-project
  source:
    repoURL: "{{ .Values.repo_url | default "https://github.com/OlgaBieliaieva/neo-devops" }}"
    path: "{{ .Values.path | default "charts/django-app" }}"
    targetRevision: "{{ .Values.targetRevision | default "lesson-9" }}"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true